version: '2'

services:
  db:
    image: mariadb
    volumes:
      - "./db-data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TMJ
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - "./site-data:/var/www/html"
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress


volumes:
  db-data:
  site-data:
